server:
  port: 12000
spring:
  application:
    name: tensuare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/doctor-fun/tensquare_dev84.git
  rabbitmq:
    host: 192.168.14.129
management: #暴露触发信息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
