server:
  port: 8003
spring:
  rabbitmq:
    host: 192.168.14.129
  application:
    name: rabbitmqtest
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
    instance:
      prefer-ip-address: true